ublox_gps_node:
  ros__parameters:
    # 제작자의 경우 아래 경로로 되었으나
    # 상황마다 다를 수 있음
    device: "/dev/ttyACM1"
    frame_id: "gps"
    config_on_startup: false
    tmode3: 0
    uart1:
      baudrate: 230400
      in: 7
      out: 1
    enable: true

    rate: 10.0        # 이게 핵심! → Hz 단위
    nav_rate: 1     # 기본값 유지
    meas_rate: 100  # ms 단위 (100ms = 10Hz)
    
    publish:
      all: false
      # GNSS 데이터 (pvt, pose 등)
      nav:
        pvt: true
        pose: true

      # GNSS 사용 여부
      gnss: true

      # IMU/ESF 관련 메시지
      esf:
        meas: true   # IMU(ESF 측정값) 토픽이 나오도록 활성화
        # status: true  # 필요한 경우 추가
        # raw: true     # 필요한 경우 추가
